### ISSUE TITLE
Bot is slow in current_build_targets

### ISSUE THREAD

**Issue by tweakimp** [Lambdanaut/Lambdanaut-sc2#2]
```python
# Count of units being trained or built
pending_units = Counter({u: self.bot.already_pending(u, all_units=True) for u in self.our_unit_types})
```
This line really slows down the bot, it is spending half its time there. I created this profile with snakeviz:
![image](https://user-images.githubusercontent.com/20489521/52691987-e235fc00-2f62-11e9-8878-4efba0a75c51.png)

**Comment by Lambdanaut** [comment]
I'm not surprised. I've been hoping to optimize it. I'll definitely add that to the todo list. Thanks!

**Comment by Lambdanaut** [comment]
I cleaned this function up a bit and optimized it some. It could be better but I'm happier with where it's at for the moment :)

Thanks again for checking it out!

**Comment by tweakimp** [comment]
So are you saying you are ready for the next profile check? :D

**Comment by Lambdanaut** [comment]
Haha if you want! I've been running snakeviz every couple weeks at this point. :)
